# Generated by Django 3.2.7 on 2021-09-22 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_projeto', '0002_alter_sensor_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cjmcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco2', models.FloatField()),
                ('etvoc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
                ('hidrogenio', models.FloatField()),
                ('luminosidade', models.FloatField()),
                ('cjmcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_projeto.cjmcu')),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Umid_Ar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umidade', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('heatIndex', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.AddField(
            model_name='medicao',
            name='tempumidar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_projeto.temp_umid_ar'),
        ),
    ]
