# Generated by Django 3.2.7 on 2021-09-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_projeto', '0003_auto_20210921_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicao',
            old_name='tempumidar',
            new_name='temperatura_umidade',
        ),
    ]
