# Generated by Django 3.2.7 on 2021-09-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projeto', '0004_rename_tempumidar_medicao_temperatura_umidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicao',
            name='temperatura_umidade',
        ),
        migrations.AddField(
            model_name='medicao',
            name='temperatura',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='umidade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='cjmcu',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Cjmcu',
        ),
        migrations.DeleteModel(
            name='Temp_Umid_Ar',
        ),
    ]
