# Generated by Django 3.2.7 on 2021-09-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projeto', '0006_auto_20210922_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicao',
            name='temperatura',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='umidade',
            field=models.FloatField(default=0),
        ),
    ]
