# Generated by Django 3.2.7 on 2021-09-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projeto', '0008_auto_20210922_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='uuid',
            field=models.TextField(default='manager', max_length=256),
        ),
    ]
