# Generated by Django 3.2.7 on 2021-10-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projeto', '0010_alter_medicao_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicao',
            name='hora',
        ),
        migrations.AddField(
            model_name='medicao',
            name='hora_millis',
            field=models.BigIntegerField(default=0),
        ),
    ]
