# Generated by Django 3.2.7 on 2021-10-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projeto', '0011_auto_20211009_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicao',
            name='hora_millis',
            field=models.BigIntegerField(),
        ),
    ]
