# Generated by Django 3.2.7 on 2021-10-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projeto', '0012_alter_medicao_hora_millis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicao',
            name='cjmcu',
        ),
        migrations.RemoveField(
            model_name='medicao',
            name='hidrogenio',
        ),
        migrations.RemoveField(
            model_name='medicao',
            name='hora_millis',
        ),
        migrations.RemoveField(
            model_name='medicao',
            name='luminosidade',
        ),
        migrations.RemoveField(
            model_name='medicao',
            name='temperatura',
        ),
        migrations.RemoveField(
            model_name='medicao',
            name='umidade',
        ),
        migrations.AddField(
            model_name='medicao',
            name='a18b20_temperatura',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='ccs811_co2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='ccs811_etvoc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='cjmcu101_luminosidade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='dht11_indiceCalor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='dht11_temperatura',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='dht11_umidade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='estacao',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='medicao',
            name='hora',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='mhrd_chuva',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='medicao',
            name='mhz19b_co2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='mq8_hidrogenio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='ph4502c_ph',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='soilmoisture_umidade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='uuid',
            field=models.TextField(default='', max_length=256),
        ),
    ]
