# Generated by Django 3.2.7 on 2021-10-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projeto', '0013_auto_20211012_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicao',
            name='estacao',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='mhrd_chuva',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='uuid',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
